### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;

### ISSUE THREAD

**Issue by johnygeorge** [networknt/json-schema-validator#81]
Doesn't work with Android Version 6.0.1. 
I am using library version `com.networknt:json-schema-validator:0.1.18`. Is there something that can be done ?

```
04-07 11:28:10.932 3799-3813/? I/TestRunner: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:241)
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:24)
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:116)
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:56)
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:49)
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:44)
        at com.networknt.schema.JsonSchemaFactory.newJsonSchema(JsonSchemaFactory.java:144)
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:165)
```

**Comment by stevehu** [comment]
@johnygeorge We are trying our best to ensure that this library is Java 6 compatible so that more users can use it. However, we don't have Andriod environment to verify that. Thanks a lot for bringing it up. 

It is addressed in https://github.com/networknt/json-schema-validator/issues/84

**Comment by stevehu** [comment]
I have just released a new version 0.1.19 and it will be soon available from Maven Central. Please verify if there are other issues in Android environment. Thanks for your help. 

https://github.com/networknt/json-schema-validator/releases/tag/0.1.19

**Comment by johnygeorge** [comment]
It works now. Thanks a lot for your quick and fast support.

**Comment by stevehu** [comment]
@johnygeorge Thanks you!!! We are all working together for the community.
